---
title: "Diogenet's Dashboard"
subtitle: "Intellectual Networks in Ancient Greece"
output: 
  flexdashboard::flex_dashboard:
        orientation: rows
        favicon: iah_classicalstudies_logo_fv_pq.png
        navbar:
          - { icon: "fa-home", href: " http://diogenet.ucsd.edu", align: right }
runtime: shiny
---

```{r global, include=FALSE}
library(flexdashboard)
library(shiny)
library(rmarkdown)
library(knitr)
library(rsconnect)
library(igraph)
library(stringi)
library(tidyverse)
library(visNetwork)
library(DT)
library(viridis)
library(heatmaply)

source("source_data.R")

```

Global Network
===================================== 

Inputs {.sidebar}
-------------------------------------

```{r}
# Re-scale sliders

# a and b are the desired initial values in the original scale 
# The function return the 0 and 10 values for the 0-10 scale
# The function is built using the a=4 and b=6 values (desired values)
rescaled_value = function(a,b,x) {
  y = ((b-a)/(6-4))*(x-4)+a
  return(y)
}

br()
h4("Network Ties")
# Selection of the edges that will appear in the relation network 
checkboxGroupInput("edges_select_global",
                   label = "Tie Type",
                   choices = list("Is teacher of" = 1, 
                                  "Is friend of" = 2, 
                                  "Is family of" = 3, 
                                  "Studied the work of" = 4, 
                                  "Sent letters to" = 5, 
                                  #"Is associated with" = 6, 
                                  "Is benefactor of" = 7),
                   selected = 1,
                   inline = FALSE)
br()

h4("Graph Layout")
selectInput(inputId = "layout_global", 
            label = "Layout Type", 
            choices = list(
                          #"layout_as_bipartite" = "layout_as_bipartite",
                          #"layout_as_star" = "layout_as_star",
                          #"layout_as_tree" = "layout_as_tree",
                          #"layout_components" = "layout_components",
                          "Nicely" = "layout_nicely",
                          "Fruchterman-Reingold" = "layout_with_fr",
                          "Kamada-Kawai" = "layout_with_kk",
                          "On sphere" = "layout_on_sphere",
                          "In Circle" = "layout_in_circle",
                          "On Grid" = "layout_on_grid"
                          #"layout_randomly" = "layout_randomly",
                          #"layout_with_dh" = "layout_with_dh",
                          #"layout_with_drl" = "layout_with_drl",
                          #"layout_with_gem" = "layout_with_gem",
                          #"layout_with_lgl" = "layout_with_lgl",
                          #"layout_with_graphopt" = "layout_with_graphopt",
                          #"layout_with_mds" = "layout_with_mds",
                          #"layout_with_sugiyama" = "layout_with_sugiyama",
                          #"layout_with_graphopt" = "layout_with_graphopt",
                          #,
                          #"layout_with_mds" = "layout_with_mds",
                          #"layout_with_sugiyama" = "layout_with_sugiyama"), selected = "layout_nicely", multiple = FALSE
                          ), 
            selected = "layout_nicely"
            )
br()

# Plot Height
h4("Appearence")
# Nodes/Label sizes
sliderInput(inputId = "label_size_global", label = "Label Size", min = 0.0, max = 10.0, value = c(4, 6),ticks = TRUE, step = 1)
sliderInput(inputId = "node_size_global", label = "Node Size", min = 0.0, max = 10.0, value = c(4, 6),ticks = TRUE, step = 1)
#hr()
#helpText("These parameters control de size range of nodes and labels. The minimum size is set to the nodes with the lowest degree, while the maximum size is set to nodes with the highest degree. The same applies for its labels")

div(message, style = "color:red")

```

Row
-------------------------------------

### Global Network

```{r, echo=FALSE}

# Function to rescale node degree
rescale <- function(x,a,b,c,d){c + (x-a)/(b-a)*(d-c)}

subset_graph  = function(edges_selected, g){
  
  # Who is the subset g_ ?
  # Depending on how many edges are selected...
  num_edge_sel = length(edges_selected)
  
  for (k in 1:num_edge_sel){
    #... and in the number of each selection
    if (edges_selected[k] == 1) edge = "is teacher of"
    if (edges_selected[k] == 2) edge = "is friend of"
    if (edges_selected[k] == 3) edge = "is family of"
    if (edges_selected[k] == 4) edge = "studied the work of"
    if (edges_selected[k] == 5) edge = "sent letters to"
    #if (edges_selected[k] == 6) edge = "is associated with"
    if (edges_selected[k] == 7) edge = "is benefactor of"
    
    #...then the subsetting rule is created dynamically
    if (num_edge_sel == 1)  edge_rule = paste0('which(E(g)$Relation == ', '\'', edge,'\'',')')
    if (num_edge_sel > 1  & k == 1) edge_rule = paste0('which(E(g)$Relation == ', '\'', edge, '\'', ' | ')
    if (num_edge_sel > 1  & k > 1 & k < num_edge_sel) edge_rule = paste0(edge_rule, 'E(g)$Relation == ', '\'', edge,'\'', ' | ')
    if (num_edge_sel > 1  & k == num_edge_sel) edge_rule = paste0(edge_rule, 'E(g)$Relation == ', '\'',edge,'\'',')')
  }
  
  # ...and the subgraph is finally created
  # If there is only one edge selected and this edge is the number 1, keep directed edges

  g_ <- subgraph.edges(g,eval(parse(text=edge_rule)))
  
  return(g_)
} 

is_directed = function(edges_selected) {
  # Default directed
  directed = TRUE
  # If "Is family of" or "is friend of" is present convert the graph to undirected
  for (i in edges_selected) {
    if ((i == 2) || (i == 3) || (i == 6)) {
      directed = as.logical(FALSE)
      break
    }
  }
  return(directed)
}


# network stores an object rendered by renderVisnetwork 
output$global_network = renderVisNetwork({
  
  # First validate if there are edges (Ties) selected
  validate(need(try(!is.null(input$edges_select_global)), "Please select at least one Tie Type"))  
  
  # Use function is_directed
  directed = is_directed(input$edges_select_global)
  
  try(g <- graph_from_data_frame(d = edges, directed=directed, vertices = nodes), silent = TRUE)
	
  # ids in nodes are es required to export to Pajek format. Just in case!
  V(g)$id = V(g)$name
  
  # ids in edges are requiered for visUpdateNodes / visRemoveNodes / visUpdateEdges / visRemoveEdges 
  E(g)$id = seq(1:length(E(g)))
  
  # Subsetting according to edges selected
  g_ = subset_graph(input$edges_select_global, g)
  
  #Set label size
  if (is.null(input$label_size_global[1])) min_label = rescaled_value(1.0,2.0,4)
  else min_label = rescaled_value(1.0,2.0,input$label_size_global[1])
  
  if (is.null(input$label_size_global[2])) max_label = rescaled_value(1.0,2.0,6)
  else max_label = rescaled_value(1.0,2.0,input$label_size_global[2])
  
  # Scaling labels
  labsize <- rescale(degree(g_), min(degree(g_)), max(degree(g_)), min_label, max_label)
  V(g_)$label.cex <- labsize
  
  # Funtion to convert igraph format to visNetwork format
  data <- toVisNetworkData(g_)
  
  # Set node size
  if (is.null(input$node_size_global[1])) min_node = rescaled_value(20.0,30.0,4)
  else min_node = rescaled_value(20.0,30.0,input$node_size_global[1])
  
  if (is.null(input$node_size_global[2])) max_node = rescaled_value(20.0,30.0,6)
  else max_node = rescaled_value(20.0,30.0,input$node_size_global[2])
  
  # Scaling nodes
  nodesize <- rescale(degree(g_), min(degree(g_)), max(degree(g_)), min_node, max_node)
  data$nodes$size = nodesize
  
  # Setting parameters straight in the data frame for visNetwork
  data$nodes$color.background = case_when(
    data$nodes$Group == "Male" ~ '#FF6347',
    data$nodes$Group == "Female" ~ '#ffa500',
    data$nodes$Group == "Place" ~ '#31e001',
    data$nodes$Group == "God" ~ '#05e2ff'
  )
  
  # Setting group in visnetwork format
  data$nodes$group = data$nodes$Group
  
  data$nodes$color.border = rep("#000000",length(data$nodes$color.background))
  
  data$nodes$color.highlight = case_when(
    data$nodes$Group == "Male" ~ '#47e3ff',
    data$nodes$Group == "Female" ~ '#4d00ff',
    data$nodes$Group == "Place" ~ '#ff0134',
    data$nodes$Group == "God" ~ '#ff4c05'
  )
  
  # Setting parameters straight in the data frame for visNetwork
  data$edges$color.color = case_when(
    data$edges$Relation == "is teacher of" ~ '#0000FF',
    data$edges$Relation == "is friend of" ~ '#228B22',
    data$edges$Relation == "is family of" ~ '#FF0000', 
    data$edges$Relation == "studied the work of" ~ '#ff01d9',
    data$edges$Relation == "sent letters to" ~ '#ffbf00',
    #data$edges$Relation == "is associated with" ~ '#14ff03',
    data$edges$Relation == "is benefactor of" ~ '#fff23c'
  )
  
  data$edges$color.highlight = case_when(
    data$edges$Relation == "is teacher of" ~ '#00ffff',
    data$edges$Relation == "is friend of" ~ '#568b22',
    data$edges$Relation == "is family of" ~ '#ff4000',
    data$edges$Relation == "studied the work of" ~ '#d9ff01',
    data$edges$Relation == "sent letters to" ~ '#8400ff',
    #data$edges$Relation == "is associated with" ~ '#ff0314',
    data$edges$Relation == "is benefactor of" ~ '#e53cff'
  )
  
  # nodes data.frame for legend
  lnodes <- data.frame(label = c("Male", "Female"),
                       shape = c( "dot"), 
                       color = c("#FF6347", "#ffa500"),
                       id = 1:2)
  
  if (directed) arrow = c("to", FALSE, FALSE, "to", "to") else  arrow = rep(as.character(FALSE),5) 
  
  # edges data.frame for legend
  ledges <- data.frame(color = c("#0000FF", "#228B22", "#FF0000", '#ff01d9','#ffbf00'),
                       label = c("is teacher of", "is friend of", "is family of", "studied the work of", "sent letters to"), 
                       arrows =arrow, 
                       font.align = "bottom")
  
  # Shows the name when hovering over the node
  data$nodes$title = paste0('<p style = "font-size:18px;font-weight:bold; font-family: verdana;">',
                            data$nodes$id,
                            '</p>', 
                            '<center><p style = "font-size:14px;font-weight:bold;font-family: verdana;color:',
                            data$nodes$color.background, 
                            ';">',
                            data$nodes$Group,
                            '</p></center>'
                            )
  
  if (directed) {
    
    # Shows the relation when hovering over the edge
    data$edges$title =  paste0('<center><p style = "font-size:14px;font-family:verdana;">',
                              data$edges$from,
                              '</p></center>', 
                              '<center><p style = "font-size:18px;font-weight:bold;font-family: verdana;color:',
                              data$edges$color.color, 
                              ';">',
                              data$edges$Relation,
                              '</p></center>', 
                              '<center><p style = "font-size:14px;font-family:verdana;">',
                              data$edges$to, 
                              '</p></center>'
                              )  
    
  } else {
    
    # Shows the relation when hovering over the edge
    data$edges$title =  paste0('<center><p style = "font-size:14px;font-family:verdana;">',
                              data$edges$to,
                              '</p></center>', 
                              '<center><p style = "font-size:18px;font-weight:bold;font-family: verdana;color:',
                              data$edges$color.color, 
                              ';">',
                              data$edges$Relation,
                              '</p></center>', 
                              '<center><p style = "font-size:14px;font-family:verdana;">',
                              data$edges$from, 
                              '</p></center>'
                              )
    
  }

  
  # Progress indicator
  withProgress(message = 'Creating graph', style = 'notification', value = 0.1, {
    Sys.sleep(0.25)
    
    incProgress(1, detail = paste("Running visnetwork"))
    
    if (input$layout_global == "layout_with_fr") {
      # Setting seed is important so the graph is always with the same configuration when starts
      set.seed(123)
      # Visnetwork graph creation
      visNetwork(nodes = data$nodes, edges = data$edges)%>%
        visNodes(shape = "dot") %>%
        visEdges(arrows =list(to = list(enabled = directed))) %>%
        #visLegend(addEdges = ledges, addNodes = lnodes, useGroups = FALSE, width = 0.1, zoom = FALSE, position = "right")%>%
        visIgraphLayout(layout = "layout_with_fr", niter= 10000) %>%
        visOptions(highlightNearest = TRUE)%>%
visInteraction(tooltipStyle = 'position: fixed;visibility:hidden;padding: 5px;white-space: nowrap;
 font-family: verdana;font-size:14px;font-color:black;background-color: white;border: 1px solid #808074;')
    } 
    else {
      if (input$layout_global == "layout_with_kk") {
        # Setting seed is important so the graph is always with the same configuration when starts
        set.seed(123)
        # Visnetwork graph creation
        visNetwork(nodes = data$nodes, edges = data$edges)%>%
          visNodes(shape = "dot") %>%
          visEdges(arrows =list(to = list(enabled = directed))) %>%
          #visLegend(addEdges = ledges, addNodes = lnodes, useGroups = FALSE, width = 0.1, zoom = FALSE, position = "right")%>%
          visIgraphLayout(layout = "layout_with_kk", maxiter = 1000) %>%
          visOptions(highlightNearest = TRUE)%>%
visInteraction(tooltipStyle = 'position: fixed;visibility:hidden;padding: 5px;white-space: nowrap;
 font-family: verdana;font-size:14px;font-color:black;background-color: white;border: 1px solid #808074;')
      } else {
        # Setting seed is important so the graph is always with the same configuration when starts
        set.seed(123)
        # Visnetwork graph creation
        visNetwork(nodes = data$nodes, edges = data$edges)%>%
          visNodes(shape = "dot") %>%
          visEdges(arrows =list(to = list(enabled = directed))) %>%
          #visLegend(addEdges = ledges, addNodes = lnodes, useGroups = FALSE, width = 0.1, zoom = FALSE, position = "right")%>%
          visIgraphLayout(layout = as.character(input$layout_global)) %>%
          visOptions(highlightNearest = TRUE)%>%
visInteraction(tooltipStyle = 'position: fixed;visibility:hidden;padding: 5px;white-space: nowrap;
 font-family: verdana;font-size:14px;font-color:black;background-color: white;border: 1px solid #808074;')
      }
    }
  })
})

# Use the visnetworkOutput function for visnetwork objects
visNetworkOutput(outputId="global_network")

```

Graph {data-navmenu="Local Network"}
===================================== 

Inputs {.sidebar}
-------------------------------------

```{r}

h4("Network Ties")
# Selection of the edges that will appear in the relation network
checkboxGroupInput("edges_select_local",
                   label = "Tie Type",
                   choices = list("Is teacher of" = 1, 
                                  "Is friend of" = 2, 
                                  "Is family of" = 3, 
                                  "Studied the work of" = 4, 
                                  "Sent letters to" = 5, 
                                  #"Is associated with" = 6, 
                                  "Is benefactor of" = 7),
                   selected = 1,
                   inline = FALSE)
br()
# Egonet configuration
h4("Egos")
# Node selection
uiOutput(outputId = "node_sel")
br()
# Order
sliderInput(inputId = "order", label = "Order", 1, 4, 2, step = 1)
# Node and Label Size
br()
h4("Appearance")
sliderInput(inputId = "label_size_local", label = "Label Size", min = 0.0, max = 10.0, value = c(4, 6),ticks = TRUE, step = 1)
sliderInput(inputId = "node_size_local", label = "Node Size", min = 0.0, max = 10.0, value = c(4, 6),ticks = TRUE, step = 1)
#hr()
#helpText("These parameters control de size range of nodes and labels. The minimum size is set to the nodes with the lowest degree, while the maximum size is set to nodes with the highest degree. The same applies for its labels")

div(message, style = "color:red")
```

Row 
-------------------------------------

### Local Network

```{r}

output$local_network = renderVisNetwork({

  validate(
    need(try(!is.null(input$edges_select_local)), "Please select at least one Tie Type")
  )

  if (!is.null(input$node_sel) && !is.null(input$order)) {

    # Use function is_directed
    directed = is_directed(input$edges_select_local)
    
    try(g <- graph_from_data_frame(d = edges, directed=directed, vertices = nodes), silent = TRUE)

    # id en nodos es necesario para exportar al formato Pajek
    V(g)$id = V(g)$name

    # id en ejes es necesario para visUpdateNodes / visRemoveNodes / visUpdateEdges / visRemoveEdges
    E(g)$id = seq(1:length(E(g)))

    # Subsetting according to edges selected
    g_ = subset_graph(input$edges_select_local, g)

    # Egonet
    d <- make_ego_graph(g_,
                        order = input$order,
                        nodes = input$node_sel,
                        mode = c("all"),
                        mindist = 0)
    
    #Set label size
    if (is.null(input$label_size_local[1])) min_label = rescaled_value(0.3,1.0,4)
    else min_label = rescaled_value(0.3,1.0,input$label_size_local[1])

    if (is.null(input$label_size_local[2])) max_label = rescaled_value(0.3,1.0,6)
    else max_label = rescaled_value(0.3,1.0,input$label_size_local[2])

    labsize <- rescale(degree(d[[1]]), min(degree(d[[1]])), max(degree(d[[1]])), min_label, max_label)
    V(d[[1]])$label.cex <- labsize

    #subTitle = paste0("Egonet of Variable ", ego_node, ", ",subTitle)

    data <- toVisNetworkData(d[[1]])

    # Set node size
    if (is.null(input$node_size_local[1])) min_node = rescaled_value(10.0,30.0,4)
    else min_node = rescaled_value(10.0,30.0,input$node_size_local[1])

    if (is.null(input$node_size_local[2])) max_node = rescaled_value(10.0,30.0,6)
    else max_node = rescaled_value(10.0,30.0,input$node_size_local[2])

    nodesize <- rescale(degree(d[[1]]), min(degree(d[[1]])), max(degree(d[[1]])), min_node, max_node)
    data$nodes$size = nodesize

    # Setting parameters straight in the data frame for visNetwork
    # Setting parameters straight in the data frame for visNetwork
    data$nodes$color.background = case_when(
      data$nodes$Group == "Male" ~ '#FF6347',
      data$nodes$Group == "Female" ~ '#ffa500',
      data$nodes$Group == "Place" ~ '#31e001',
      data$nodes$Group == "God" ~ '#05e2ff'
    )

    # Setting group in visnetwork format
    data$nodes$group = data$nodes$Group

    data$nodes$color.border = rep("#000000",length(data$nodes$color.background))

    data$nodes$color.highlight = case_when(
      data$nodes$Group == "Male" ~ '#47e3ff',
      data$nodes$Group == "Female" ~ '#4d00ff',
      data$nodes$Group == "Place" ~ '#ff0134',
      data$nodes$Group == "God" ~ '#ff4c05'
    )
    
    # Setting parameters straight in the data frame for visNetwork
    data$edges$color.color = case_when(
      data$edges$Relation == "is teacher of" ~ '#0000FF',
      data$edges$Relation == "is friend of" ~ '#228B22',
      data$edges$Relation == "is family of" ~ '#FF0000', 
      data$edges$Relation == "studied the work of" ~ '#ff01d9',
      data$edges$Relation == "sent letters to" ~ '#ffbf00',
      #data$edges$Relation == "is associated with" ~ '#14ff03',
      data$edges$Relation == "is benefactor of" ~ '#fff23c'
    )
    
    data$edges$color.highlight = case_when(
      data$edges$Relation == "is teacher of" ~ '#00ffff',
      data$edges$Relation == "is friend of" ~ '#568b22',
      data$edges$Relation == "is family of" ~ '#ff4000',
      data$edges$Relation == "studied the work of" ~ '#d9ff01',
      data$edges$Relation == "sent letters to" ~ '#8400ff',
      #data$edges$Relation == "is associated with" ~ '#ff0314',
      data$edges$Relation == "is benefactor of" ~ '#e53cff'
    )
  
    # nodes data.frame for legend
    lnodes <- data.frame(label = c("Male", "Female"),
                         shape = c( "dot"), 
                         color = c("#FF6347", "#ffa500"),
                         id = 1:2)
    
    if (directed) arrow = c("to", FALSE, FALSE, "to", "to") else  arrow = rep(as.character(FALSE),5) 
    
    # edges data.frame for legend
    ledges <- data.frame(color = c("#0000FF", "#228B22", "#FF0000", '#ff01d9','#ffbf00'),
                         label = c("is teacher of", "is friend of", "is family of", "studied the work of", "sent letters to"), 
                         arrows = arrow, 
                         font.align = "bottom")
    
    # Shows the name when hovering over the node
    data$nodes$title = paste0('<p style = "font-size:18px;font-weight:bold; font-family: verdana;">',
                              data$nodes$id,
                              '</p>', 
                              '<center><p style = "font-size:14px;font-weight:bold;font-family: verdana;color:',
                              data$nodes$color.background, 
                              ';">',
                              data$nodes$Group,
                              '</p></center>'
                              )
    
    if (directed) {
      
      # Shows the relation when hovering over the edge
      data$edges$title =  paste0('<center><p style = "font-size:14px;font-family:verdana;">',
                                data$edges$from,
                                '</p></center>', 
                                '<center><p style = "font-size:18px;font-weight:bold;font-family: verdana;color:',
                                data$edges$color.color, 
                                ';">',
                                data$edges$Relation,
                                '</p></center>', 
                                '<center><p style = "font-size:14px;font-family:verdana;">',
                                data$edges$to, 
                                '</p></center>'
                                )  
      
    } else {
      
      # Shows the relation when hovering over the edge
      data$edges$title =  paste0('<center><p style = "font-size:14px;font-family:verdana;">',
                                data$edges$to,
                                '</p></center>', 
                                '<center><p style = "font-size:18px;font-weight:bold;font-family: verdana;color:',
                                data$edges$color.color, 
                                ';">',
                                data$edges$Relation,
                                '</p></center>', 
                                '<center><p style = "font-size:14px;font-family:verdana;">',
                                data$edges$from, 
                                '</p></center>'
                                )
      
    }

    withProgress(message = 'Creating graph', style = 'notification', value = 0.1, {
      Sys.sleep(0.25)

      incProgress(1, detail = paste("Running visnetwork"))
      
      # Setting seed is important so the graph is always with the same configuration when starts
      set.seed(123)

	    visNetwork(nodes = data$nodes, edges = data$edges)%>%
	      visNodes(shape = "dot") %>%
	      visEdges(arrows =list(to = list(enabled = directed)),
	               color = list(color = "gray",
	                            highlight = "red")) %>%
        #visLegend(addEdges = ledges, addNodes = lnodes, useGroups = FALSE, width = 0.1, zoom = FALSE, position = "right")%>%
	      visIgraphLayout()%>%
	      visOptions(highlightNearest = TRUE)%>%
visInteraction(tooltipStyle = 'position: fixed;visibility:hidden;padding: 5px;white-space: nowrap;
 font-family: verdana;font-size:14px;font-color:black;background-color: white;border: 1px solid #808074;')
	    })
  }
})

# This function creates the selectInput object dynamically.
# The options for nodes in the list depends on the edges selected

output$node_sel <- renderUI({

  validate(
    need(try(!is.null(input$edges_select_local)), "Select at least one Tie")
  )
  
  all_nodes = c()

  if (1 %in% input$edges_select_local){
      all_nodes = c(all_nodes, 
                    as.character(edges$Source[which(edges$Relation == "is teacher of")]),
                    as.character(edges$Target[which(edges$Relation == "is teacher of")]))
      }

  if (2 %in% input$edges_select_local){
    all_nodes = c(all_nodes, 
                  as.character(edges$Source[which(edges$Relation == "is friend of")]),
                  as.character(edges$Target[which(edges$Relation == "is friend of")]))
    }
      
  if (3 %in% input$edges_select_local){
    all_nodes = c(all_nodes, 
                  as.character(edges$Source[which(edges$Relation == "is family of")]),
                  as.character(edges$Target[which(edges$Relation == "is family of")]))
  }
  
  if (4 %in% input$edges_select_local){
    all_nodes = c(all_nodes, 
                  as.character(edges$Source[which(edges$Relation == "studied the work of")]),
                  as.character(edges$Target[which(edges$Relation == "studied the work of")]))
  }
  
  if (5 %in% input$edges_select_local){
    all_nodes = c(all_nodes, 
                  as.character(edges$Source[which(edges$Relation == "sent letters to")]),
                  as.character(edges$Target[which(edges$Relation == "sent letters to")]))
  }
  
  if (7 %in% input$edges_select_local){
  all_nodes = c(all_nodes, 
                as.character(edges$Source[which(edges$Relation == "is benefactor of")]),
                as.character(edges$Target[which(edges$Relation == "is benefactor of")]))
  }
    
  all_nodes = sort(unique(all_nodes))
    
  if (!is.null(input$node_sel)) selectInput(inputId = "node_sel", label = "Node", choices = all_nodes, selected = input$node_sel)
  else selectInput(inputId = "node_sel", label = "Node", choices = all_nodes, selected = "Plato")
})

visNetworkOutput(outputId="local_network")

```

Graph + Centrality {data-navmenu="Local Network" data-orientation="columns"}
===================================== 

Inputs {.sidebar}
-------------------------------------

```{r}

h4("Network Ties")
# Selection of the edges that will appear in the relation network
checkboxGroupInput("edges_select_local_m",
                   label = "Tie Type",
                   choices = list("Is teacher of" = 1, 
                                  "Is friend of" = 2, 
                                  "Is family of" = 3, 
                                  "Studied the work of" = 4, 
                                  "Sent letters to" = 5, 
                                  #"Is associated with" = 6, 
                                  "Is benefactor of" = 7),
                   selected = 1,
                   inline = FALSE)
br()
# Egonet configuration
h4("Egos")
# Node selection
uiOutput(outputId = "node_sel_m")
br()
# Order
sliderInput(inputId = "order_m", label = "Order", 1, 4, 2, step = 1)
# Node and Label Size
br()
h4("Appearance")
sliderInput(inputId = "label_size_local_m", label = "Label Size", min = 0.0, max = 10.0, value = c(4, 6),ticks = TRUE, step = 1)
sliderInput(inputId = "node_size_local_m", label = "Node Size", min = 0.0, max = 10.0, value = c(4, 6),ticks = TRUE, step = 1)
br()
h4("Visualization in Graph")
selectInput("variable_type", "Variable:",
                c("Degree" = "degree",
                  "Betweenness" = "betweenness",
                  "Closeness" = "closeness",
                  "Eigenvector" = "eigenvector"))
 
#hr()
#helpText("These parameters control de size range of nodes and labels. The minimum size is set to the nodes with the lowest degree, while the maximum size is set to nodes with the highest degree. The same applies for its labels")

div(message, style = "color:red")
```

Column {.tabset .tabset-fade data-width=600}
-------------------------------------

```{r, echo = FALSE}

directed = reactive({
  return(is_directed(input$edges_select_local_m))
})

d = reactive({
  
  if (!is.null(input$node_sel_m) && !is.null(input$order_m)) {

    # Use function is_directed in reactive directed
    directed = directed()
    
    try(g <- graph_from_data_frame(d = edges, directed=directed, vertices = nodes), silent = TRUE)

    # id en nodos es necesario para exportar al formato Pajek
    V(g)$id = V(g)$name

    # id en ejes es necesario para visUpdateNodes / visRemoveNodes / visUpdateEdges / visRemoveEdges
    E(g)$id = seq(1:length(E(g)))

    # Subsetting according to edges selected
    g_ = subset_graph(input$edges_select_local_m, g)

    # Egonet
    local_ntwk <- make_ego_graph(g_,
                        order = input$order_m,
                        nodes = input$node_sel_m,
                        mode = c("all"),
                        mindist = 0)
  return(local_ntwk)
  }
})

values = reactive({
    
    validate(
      need(try(!is.null(input$edges_select_local_m)), "Please select at least one Tie Type")
    )
  
    if (!is.null(input$node_sel_m) && !is.null(input$order_m)) {
      d = d()
      val =  data.frame(degree = degree(d[[1]]),
                         betweenness = as.numeric(format(betweenness(d[[1]]), digits = 3, nsmall = 3)),
                         closeness = as.numeric(format(closeness(d[[1]]), digits = 3, nsmall = 3)),
                         eigenvector = as.numeric(format(eigen_centrality(d[[1]])$vector, digits = 3, nsmall = 3)))
      val = val[order(val$degree, decreasing = TRUE),]
      return(val)
    }
})

centr = reactive({
  
  validate(
    need(try(!is.null(input$edges_select_local_m)), "Please select at least one Tie Type")
  )
  
  if (!is.null(input$node_sel_m) && !is.null(input$order_m)) {
    d = d()
    centr_ = data.frame(degree = centralization.degree(d[[1]])$centralization[1],
                     betweenness = centralization.betweenness(d[[1]])$centralization[1],
                     closeness = centralization.closeness(d[[1]])$centralization[1],
                     eigenvector = centralization.evcent(d[[1]])$centralization[1]
                     )
    return(centr_)
  }
})

output$table_values = renderDT(return(values()), options = list(pageLength = 10))

output$table_centr = renderTable({return(centr())}, align = 'c', width = NULL)

# This function creates the selectInput object dynamically.
# The options for nodes in the list depends on the edges selected

output$node_sel_m <- renderUI({

  validate(
    need(try(!is.null(input$edges_select_local_m)), "Select at least one Tie")
  )
  
  all_nodes = c()

  if (1 %in% input$edges_select_local_m){
      all_nodes = c(all_nodes, 
                    as.character(edges$Source[which(edges$Relation == "is teacher of")]),
                    as.character(edges$Target[which(edges$Relation == "is teacher of")]))
      }

  if (2 %in% input$edges_select_local_m){
    all_nodes = c(all_nodes, 
                  as.character(edges$Source[which(edges$Relation == "is friend of")]),
                  as.character(edges$Target[which(edges$Relation == "is friend of")]))
    }
      
  if (3 %in% input$edges_select_local_m){
    all_nodes = c(all_nodes, 
                  as.character(edges$Source[which(edges$Relation == "is family of")]),
                  as.character(edges$Target[which(edges$Relation == "is family of")]))
  }
  
  if (4 %in% input$edges_select_local_m){
    all_nodes = c(all_nodes, 
                  as.character(edges$Source[which(edges$Relation == "studied the work of")]),
                  as.character(edges$Target[which(edges$Relation == "studied the work of")]))
  }
  
  if (5 %in% input$edges_select_local_m){
    all_nodes = c(all_nodes, 
                  as.character(edges$Source[which(edges$Relation == "sent letters to")]),
                  as.character(edges$Target[which(edges$Relation == "sent letters to")]))
  }
  
  if (7 %in% input$edges_select_local_m){
  all_nodes = c(all_nodes, 
                as.character(edges$Source[which(edges$Relation == "is benefactor of")]),
                as.character(edges$Target[which(edges$Relation == "is benefactor of")]))
  }
    
  all_nodes = sort(unique(all_nodes))
    
  if (!is.null(input$node_sel_m)) selectInput(inputId = "node_sel_m", label = "Node", choices = all_nodes, selected = input$node_sel_m)
  else selectInput(inputId = "node_sel_m", label = "Node", choices = all_nodes, selected = "Plato")
})

```

### Graph

```{r, echo = FALSE}

output$local_network_monitor = renderVisNetwork({
  
  validate(
    need(try(!is.null(input$edges_select_local_m)), "Please select at least one Tie Type")
  )

  if (!is.null(input$node_sel_m) && !is.null(input$order_m)) {
    
    # Update reactive values
    directed = directed()
    d = d()
    
    if (input$variable_type == 'degree'){
      
      #Set label size
      if (is.null(input$label_size_local_m[1])) min_label = rescaled_value(0.3,1.0,4)
      else min_label = rescaled_value(0.3,1.0,input$label_size_local_m[1])
  
      if (is.null(input$label_size_local_m[2])) max_label = rescaled_value(0.3,1.0,6)
      else max_label = rescaled_value(0.3,1.0,input$label_size_local_m[2])
      
      labsize <- rescale(degree(d[[1]]), min(degree(d[[1]])), max(degree(d[[1]])), min_label, max_label)
      V(d[[1]])$label.cex <- labsize
  
      #subTitle = paste0("Egonet of Variable ", ego_node, ", ",subTitle)
  
      data <- toVisNetworkData(d[[1]])
  
      # Set node size
      if (is.null(input$node_size_local_m[1])) min_node = rescaled_value(10.0,30.0,4)
      else min_node = rescaled_value(10.0,30.0,input$node_size_local_m[1])
  
      if (is.null(input$node_size_local_m[2])) max_node = rescaled_value(10.0,30.0,6)
      else max_node = rescaled_value(10.0,30.0,input$node_size_local_m[2])
  
      nodesize <- rescale(degree(d[[1]]), min(degree(d[[1]])), max(degree(d[[1]])), min_node, max_node)
      data$nodes$size = nodesize
  
      min_deg = min(degree(d[[1]]))
      max_deg = max(degree(d[[1]]))
      n_col =  50
      node_vir_col = viridis(n = n_col, begin = 0, end = 1, direction = 1, option = "plasma")
      
      # x in this function is degree
      col_index = function(x) {((n_col -1)/(max_deg - min_deg))*(x-min_deg)+1}
    
      returnColor = function(x) {substr(node_vir_col[col_index(x)],1,nchar(node_vir_col[col_index(x)])-2)}
       
      
      # Setting parameters straight in the data frame for visNetwork
      data$nodes$color.background = sapply(degree(d[[1]]), FUN = returnColor)
      
      data$nodes$degree = degree(d[[1]])
      
      # Setting group in visnetwork format
      data$nodes$group = data$nodes$Group
  
      data$nodes$color.border = sapply(degree(d[[1]]), FUN = returnColor)
  
      data$nodes$color.highlight = case_when(
        data$nodes$Group == "Male" ~ '#47e3ff',
        data$nodes$Group == "Female" ~ '#4d00ff',
        data$nodes$Group == "Place" ~ '#ff0134',
        data$nodes$Group == "God" ~ '#ff4c05'
      )
      
      # Setting parameters straight in the data frame for visNetwork
      data$edges$color.color = rep("gray",length(data$edges$Relation))
      
      data$edges$color.highlight = rep("gray",length(data$edges$Relation))
    
      # nodes data.frame for legend
      lnodes <- data.frame(label = c("Male", "Female"),
                           shape = c( "dot"), 
                           color = c("#FF6347", "#ffa500"),
                           id = 1:2)
      
      if (directed) arrow = c("to", FALSE, FALSE, "to", "to") else  arrow = rep(as.character(FALSE),5) 
      
      # edges data.frame for legend
      ledges <- data.frame(color = c("#0000FF", "#228B22", "#FF0000", '#ff01d9','#ffbf00'),
                           label = c("is teacher of", "is friend of", "is family of", "studied the work of", "sent letters to"), 
                           arrows = arrow, 
                           font.align = "bottom")
      
      # Shows the name when hovering over the node
      data$nodes$title = paste0('<p style = "font-size:18px;font-weight:bold; font-family: verdana;">',
                                data$nodes$id,
                                '</p>', 
                                '<center><p style = "font-size:14px;font-weight:bold;font-family: verdana;color:',
                                data$nodes$color.background, 
                                ';">',
                                data$nodes$degree,
                                '</p></center>'
                                )
      
      if (directed) {
        
        # Shows the relation when hovering over the edge
        data$edges$title =  paste0('<center><p style = "font-size:14px;font-family:verdana;">',
                                  data$edges$from,
                                  '</p></center>', 
                                  '<center><p style = "font-size:18px;font-weight:bold;font-family: verdana;color:',
                                  data$edges$color.color, 
                                  ';">',
                                  data$edges$Relation,
                                  '</p></center>', 
                                  '<center><p style = "font-size:14px;font-family:verdana;">',
                                  data$edges$to, 
                                  '</p></center>'
                                  )  
        
      } else {
        
        # Shows the relation when hovering over the edge
        data$edges$title =  paste0('<center><p style = "font-size:14px;font-family:verdana;">',
                                  data$edges$to,
                                  '</p></center>', 
                                  '<center><p style = "font-size:18px;font-weight:bold;font-family: verdana;color:',
                                  data$edges$color.color, 
                                  ';">',
                                  data$edges$Relation,
                                  '</p></center>', 
                                  '<center><p style = "font-size:14px;font-family:verdana;">',
                                  data$edges$from, 
                                  '</p></center>'
                                  )
        
      }
  
      withProgress(message = 'Creating graph', style = 'notification', value = 0.1, {
        Sys.sleep(0.25)
  
        incProgress(1, detail = paste("Running visnetwork"))
        
        # Setting seed is important so the graph is always with the same configuration when starts
        set.seed(123)
  
  	    ntw = visNetwork(nodes = data$nodes, edges = data$edges)%>%
  	      visNodes(shape = "dot") %>%
  	      visEdges(arrows =list(to = list(enabled = directed)),
  	               color = list(color = "gray",
  	                            highlight = "red")) %>%
          #visLegend(addEdges = ledges, addNodes = lnodes, useGroups = FALSE, width = 0.1, zoom = FALSE, position = "right")%>%
  	      visIgraphLayout()%>%
  	      visOptions(highlightNearest = TRUE)%>%
visInteraction(tooltipStyle = 'position: fixed;visibility:hidden;padding: 5px;white-space: nowrap;
   font-family: verdana;font-size:14px;font-color:black;background-color: white;border: 1px solid #808074;')
  	    }) 
    }
    if (input$variable_type == 'betweenness'){

      #Set label size
      if (is.null(input$label_size_local_m[1])) min_label = rescaled_value(0.3,1.0,4)
      else min_label = rescaled_value(0.3,1.0,input$label_size_local_m[1])
  
      if (is.null(input$label_size_local_m[2])) max_label = rescaled_value(0.3,1.0,6)
      else max_label = rescaled_value(0.3,1.0,input$label_size_local_m[2])
  
      labsize <- rescale(degree(d[[1]]), min(degree(d[[1]])), max(degree(d[[1]])), min_label, max_label)
      V(d[[1]])$label.cex <- labsize
  
      data <- toVisNetworkData(d[[1]])
  
      # Set node size
      if (is.null(input$node_size_local_m[1])) min_node = rescaled_value(10.0,30.0,4)
      else min_node = rescaled_value(10.0,30.0,input$node_size_local_m[1])
  
      if (is.null(input$node_size_local_m[2])) max_node = rescaled_value(10.0,30.0,6)
      else max_node = rescaled_value(10.0,30.0,input$node_size_local_m[2])
  
      nodesize <- rescale(degree(d[[1]]), min(degree(d[[1]])), max(degree(d[[1]])), min_node, max_node)
      data$nodes$size = nodesize
  
      min_bet = min(betweenness(d[[1]]))
      max_bet = max(betweenness(d[[1]]))
      n_col =  50
      node_vir_col = viridis(n = n_col, begin = 0, end = 1, direction = 1, option = "plasma")
      
      # x in this function is degree
      col_index = function(x) {((n_col -1)/(max_bet - min_bet))*(x-min_bet)+1}
    
      returnColor = function(x) {substr(node_vir_col[col_index(x)],1,nchar(node_vir_col[col_index(x)])-2)}
       
      # Setting parameters straight in the data frame for visNetwork
      data$nodes$color.background = sapply(betweenness(d[[1]]), FUN = returnColor)
      
      data$nodes$betweenness = format(betweenness(d[[1]]), digits = 3, nsmall = 3) 
  
      # Setting group in visnetwork format
      data$nodes$group = data$nodes$Group
  
      data$nodes$color.border = sapply(betweenness(d[[1]]), FUN = returnColor)
  
      data$nodes$color.highlight = case_when(
        data$nodes$Group == "Male" ~ '#47e3ff',
        data$nodes$Group == "Female" ~ '#4d00ff',
        data$nodes$Group == "Place" ~ '#ff0134',
        data$nodes$Group == "God" ~ '#ff4c05'
      )
      
      # Setting parameters straight in the data frame for visNetwork
      data$edges$color.color = rep("gray",length(data$edges$Relation))
      
      data$edges$color.highlight = rep("gray",length(data$edges$Relation))
    
      # nodes data.frame for legend
      lnodes <- data.frame(label = c("Male", "Female"),
                           shape = c( "dot"), 
                           color = c("#FF6347", "#ffa500"),
                           id = 1:2)
      
      if (directed) arrow = c("to", FALSE, FALSE, "to", "to") else  arrow = rep(as.character(FALSE),5) 
      
      # edges data.frame for legend
      ledges <- data.frame(color = c("#0000FF", "#228B22", "#FF0000", '#ff01d9','#ffbf00'),
                           label = c("is teacher of", "is friend of", "is family of", "studied the work of", "sent letters to"), 
                           arrows = arrow, 
                           font.align = "bottom")
      
      # Shows the name when hovering over the node
      data$nodes$title = paste0('<p style = "font-size:18px;font-weight:bold; font-family: verdana;">',
                                data$nodes$id,
                                '</p>', 
                                '<center><p style = "font-size:14px;font-weight:bold;font-family: verdana;color:',
                                data$nodes$color.background, 
                                ';">',
                                data$nodes$betweenness,
                                '</p></center>'
                                )
      
      if (directed) {
        
        # Shows the relation when hovering over the edge
        data$edges$title =  paste0('<center><p style = "font-size:14px;font-family:verdana;">',
                                  data$edges$from,
                                  '</p></center>', 
                                  '<center><p style = "font-size:18px;font-weight:bold;font-family: verdana;color:',
                                  data$edges$color.color, 
                                  ';">',
                                  data$edges$Relation,
                                  '</p></center>', 
                                  '<center><p style = "font-size:14px;font-family:verdana;">',
                                  data$edges$to, 
                                  '</p></center>'
                                  )  
        
      } else {
        
        # Shows the relation when hovering over the edge
        data$edges$title =  paste0('<center><p style = "font-size:14px;font-family:verdana;">',
                                  data$edges$to,
                                  '</p></center>', 
                                  '<center><p style = "font-size:18px;font-weight:bold;font-family: verdana;color:',
                                  data$edges$color.color, 
                                  ';">',
                                  data$edges$Relation,
                                  '</p></center>', 
                                  '<center><p style = "font-size:14px;font-family:verdana;">',
                                  data$edges$from, 
                                  '</p></center>'
                                  )
        
      }
  
      withProgress(message = 'Creating graph', style = 'notification', value = 0.1, {
        Sys.sleep(0.25)
  
        incProgress(1, detail = paste("Running visnetwork"))
        
        # Setting seed is important so the graph is always with the same configuration when starts
        set.seed(123)
  
  	    ntw = visNetwork(nodes = data$nodes, edges = data$edges)%>%
  	      visNodes(shape = "dot") %>%
  	      visEdges(arrows =list(to = list(enabled = directed)),
  	               color = list(color = "gray",
  	                            highlight = "red")) %>%
          #visLegend(addEdges = ledges, addNodes = lnodes, useGroups = FALSE, width = 0.1, zoom = FALSE, position = "right")%>%
  	      visIgraphLayout()%>%
  	      visOptions(highlightNearest = TRUE)%>%
  visInteraction(tooltipStyle = 'position: fixed;visibility:hidden;padding: 5px;white-space: nowrap;
   font-family: verdana;font-size:14px;font-color:black;background-color: white;border: 1px solid #808074;')
  	    })
    }
    if (input$variable_type == 'closeness'){
    
      #Set label size
      if (is.null(input$label_size_local_m[1])) min_label = rescaled_value(0.3,1.0,4)
      else min_label = rescaled_value(0.3,1.0,input$label_size_local_m[1])
  
      if (is.null(input$label_size_local_m[2])) max_label = rescaled_value(0.3,1.0,6)
      else max_label = rescaled_value(0.3,1.0,input$label_size_local_m[2])
  
      labsize <- rescale(degree(d[[1]]), min(degree(d[[1]])), max(degree(d[[1]])), min_label, max_label)
      V(d[[1]])$label.cex <- labsize
  
      data <- toVisNetworkData(d[[1]])
  
      # Set node size
      if (is.null(input$node_size_local_m[1])) min_node = rescaled_value(10.0,30.0,4)
      else min_node = rescaled_value(10.0,30.0,input$node_size_local_m[1])
  
      if (is.null(input$node_size_local_m[2])) max_node = rescaled_value(10.0,30.0,6)
      else max_node = rescaled_value(10.0,30.0,input$node_size_local_m[2])
  
      nodesize <- rescale(degree(d[[1]]), min(degree(d[[1]])), max(degree(d[[1]])), min_node, max_node)
      data$nodes$size = nodesize
  
      min_close = min(closeness(d[[1]]))
      max_close = max(closeness(d[[1]]))
      n_col =  50
      node_vir_col = viridis(n = n_col, begin = 0, end = 1, direction = 1, option = "plasma")
      
      # x in this function is degree
      col_index = function(x) {((n_col -1)/(max_close - min_close))*(x-min_close)+1}
    
      returnColor = function(x) {substr(node_vir_col[col_index(x)],1,nchar(node_vir_col[col_index(x)])-2)}
       
      # Setting parameters straight in the data frame for visNetwork
      data$nodes$color.background = sapply(closeness(d[[1]]), FUN = returnColor)
      
      data$nodes$closeness =  format(closeness(d[[1]]), digits = 3, nsmall = 3) 
      
      # Setting group in visnetwork format
      data$nodes$group = data$nodes$Group
  
      data$nodes$color.border = sapply(closeness(d[[1]]), FUN = returnColor)
  
      data$nodes$color.highlight = case_when(
        data$nodes$Group == "Male" ~ '#47e3ff',
        data$nodes$Group == "Female" ~ '#4d00ff',
        data$nodes$Group == "Place" ~ '#ff0134',
        data$nodes$Group == "God" ~ '#ff4c05'
      )
      
      # Setting parameters straight in the data frame for visNetwork
      data$edges$color.color = rep("gray",length(data$edges$Relation))
      
      data$edges$color.highlight = rep("gray",length(data$edges$Relation))
    
      # nodes data.frame for legend
      lnodes <- data.frame(label = c("Male", "Female"),
                           shape = c( "dot"), 
                           color = c("#FF6347", "#ffa500"),
                           id = 1:2)
      
      if (directed) arrow = c("to", FALSE, FALSE, "to", "to") else  arrow = rep(as.character(FALSE),5) 
      
      # edges data.frame for legend
      ledges <- data.frame(color = c("#0000FF", "#228B22", "#FF0000", '#ff01d9','#ffbf00'),
                           label = c("is teacher of", "is friend of", "is family of", "studied the work of", "sent letters to"), 
                           arrows = arrow, 
                           font.align = "bottom")
      
      # Shows the name when hovering over the node
      data$nodes$title = paste0('<p style = "font-size:18px;font-weight:bold; font-family: verdana;">',
                                data$nodes$id,
                                '</p>', 
                                '<center><p style = "font-size:14px;font-weight:bold;font-family: verdana;color:',
                                data$nodes$color.background, 
                                ';">',
                                data$nodes$closeness,
                                '</p></center>'
                                )
      
      if (directed) {
        
        # Shows the relation when hovering over the edge
        data$edges$title =  paste0('<center><p style = "font-size:14px;font-family:verdana;">',
                                  data$edges$from,
                                  '</p></center>', 
                                  '<center><p style = "font-size:18px;font-weight:bold;font-family: verdana;color:',
                                  data$edges$color.color, 
                                  ';">',
                                  data$edges$Relation,
                                  '</p></center>', 
                                  '<center><p style = "font-size:14px;font-family:verdana;">',
                                  data$edges$to, 
                                  '</p></center>'
                                  )  
        
      } else {
        
        # Shows the relation when hovering over the edge
        data$edges$title =  paste0('<center><p style = "font-size:14px;font-family:verdana;">',
                                  data$edges$to,
                                  '</p></center>', 
                                  '<center><p style = "font-size:18px;font-weight:bold;font-family: verdana;color:',
                                  data$edges$color.color, 
                                  ';">',
                                  data$edges$Relation,
                                  '</p></center>', 
                                  '<center><p style = "font-size:14px;font-family:verdana;">',
                                  data$edges$from, 
                                  '</p></center>'
                                  )
        
      }
  
      withProgress(message = 'Creating graph', style = 'notification', value = 0.1, {
        Sys.sleep(0.25)
  
        incProgress(1, detail = paste("Running visnetwork"))
        
        # Setting seed is important so the graph is always with the same configuration when starts
        set.seed(123)
  
  	    ntw = visNetwork(nodes = data$nodes, edges = data$edges)%>%
  	      visNodes(shape = "dot") %>%
  	      visEdges(arrows =list(to = list(enabled = directed)),
  	               color = list(color = "gray",
  	                            highlight = "red")) %>%
          #visLegend(addEdges = ledges, addNodes = lnodes, useGroups = FALSE, width = 0.1, zoom = FALSE, position = "right")%>%
  	      visIgraphLayout()%>%
  	      visOptions(highlightNearest = TRUE)%>%
  visInteraction(tooltipStyle = 'position: fixed;visibility:hidden;padding: 5px;white-space: nowrap;
   font-family: verdana;font-size:14px;font-color:black;background-color: white;border: 1px solid #808074;')
  	    })
    }
    if (input$variable_type == 'eigenvector'){

      #Set label size
      if (is.null(input$label_size_local_m[1])) min_label = rescaled_value(0.3,1.0,4)
      else min_label = rescaled_value(0.3,1.0,input$label_size_local_m[1])
  
      if (is.null(input$label_size_local_m[2])) max_label = rescaled_value(0.3,1.0,6)
      else max_label = rescaled_value(0.3,1.0,input$label_size_local_m[2])
  
      labsize <- rescale(degree(d[[1]]), min(degree(d[[1]])), max(degree(d[[1]])), min_label, max_label)
      V(d[[1]])$label.cex <- labsize
  
      data <- toVisNetworkData(d[[1]])
  
      # Set node size
      if (is.null(input$node_size_local_m[1])) min_node = rescaled_value(10.0,30.0,4)
      else min_node = rescaled_value(10.0,30.0,input$node_size_local_m[1])
  
      if (is.null(input$node_size_local_m[2])) max_node = rescaled_value(10.0,30.0,6)
      else max_node = rescaled_value(10.0,30.0,input$node_size_local_m[2])

      nodesize <- rescale(degree(d[[1]]), min(degree(d[[1]])), max(degree(d[[1]])), min_node, max_node)
      data$nodes$size = nodesize
  
      min_eigen = min(eigen_centrality(d[[1]])$vector)
      max_eigen = max(eigen_centrality(d[[1]])$vector)
      n_col =  50
      node_vir_col = viridis(n = n_col, begin = 0, end = 1, direction = 1, option = "plasma")
      
      # x in this function is eigen_centrality
      col_index_evc = function(x) {((n_col -1.00)/(max_eigen - min_eigen))*(x - min_eigen)+1.00}
      
      col_index_evc_data = col_index_evc(eigen_centrality(d[[1]])$vector)
    
      returnColor_evc = function(x) {substr(node_vir_col[x],1,nchar(node_vir_col[x])-2)}
      
      # Setting parameters straight in the data frame for visNetwork
      data$nodes$color.background = sapply(ceiling(col_index_evc_data), FUN = returnColor_evc)
      
      data$nodes$eigen = format(eigen_centrality(d[[1]])$vector, digits = 3, nsmall = 3)
      
      data$nodes$color.border = sapply(ceiling(col_index_evc_data), FUN = returnColor_evc)
  
      data$nodes$color.highlight = case_when(
        data$nodes$Group == "Male" ~ '#47e3ff',
        data$nodes$Group == "Female" ~ '#4d00ff',
        data$nodes$Group == "Place" ~ '#ff0134',
        data$nodes$Group == "God" ~ '#ff4c05'
      )
      
      # Setting parameters straight in the data frame for visNetwork
      data$edges$color.color = rep("gray",length(data$edges$Relation))
      
      data$edges$color.highlight = rep("gray",length(data$edges$Relation))
    
      # nodes data.frame for legend
      lnodes <- data.frame(label = c("Male", "Female"),
                           shape = c( "dot"), 
                           color = c("#FF6347", "#ffa500"),
                           id = 1:2)
      
      if (directed) arrow = c("to", FALSE, FALSE, "to", "to") else  arrow = rep(as.character(FALSE),5) 
      
      # edges data.frame for legend
      ledges <- data.frame(color = c("#0000FF", "#228B22", "#FF0000", '#ff01d9','#ffbf00'),
                           label = c("is teacher of", "is friend of", "is family of", "studied the work of", "sent letters to"), 
                           arrows = arrow, 
                           font.align = "bottom")
      
      # Shows the name when hovering over the node
      data$nodes$title = paste0('<p style = "font-size:18px;font-weight:bold; font-family: verdana;">',
                                data$nodes$id,
                                '</p>', 
                                '<center><p style = "font-size:14px;font-weight:bold;font-family: verdana;color:',
                                data$nodes$color.background, 
                                ';">',
                                data$nodes$eigen,
                                '</p></center>'
                                )
      
      if (directed) {
        
        # Shows the relation when hovering over the edge
        data$edges$title =  paste0('<center><p style = "font-size:14px;font-family:verdana;">',
                                  data$edges$from,
                                  '</p></center>', 
                                  '<center><p style = "font-size:18px;font-weight:bold;font-family: verdana;color:',
                                  data$edges$color.color, 
                                  ';">',
                                  data$edges$Relation,
                                  '</p></center>', 
                                  '<center><p style = "font-size:14px;font-family:verdana;">',
                                  data$edges$to, 
                                  '</p></center>'
                                  )  
        
      } else {
        
        # Shows the relation when hovering over the edge
        data$edges$title =  paste0('<center><p style = "font-size:14px;font-family:verdana;">',
                                  data$edges$to,
                                  '</p></center>', 
                                  '<center><p style = "font-size:18px;font-weight:bold;font-family: verdana;color:',
                                  data$edges$color.color, 
                                  ';">',
                                  data$edges$Relation,
                                  '</p></center>', 
                                  '<center><p style = "font-size:14px;font-family:verdana;">',
                                  data$edges$from, 
                                  '</p></center>'
                                  )
        
      }
  
      withProgress(message = 'Creating graph', style = 'notification', value = 0.1, {
        Sys.sleep(0.25)
  
        incProgress(1, detail = paste("Running visnetwork"))
        
        # Setting seed is important so the graph is always with the same configuration when starts
        set.seed(123)
  
  	    ntw = visNetwork(nodes = data$nodes, edges = data$edges)%>%
  	      visNodes(shape = "dot") %>%
  	      visEdges(arrows =list(to = list(enabled = directed)),
  	               color = list(color = "gray",
  	                            highlight = "red")) %>%
          #visLegend(addEdges = ledges, addNodes = lnodes, useGroups = FALSE, width = 0.1, zoom = FALSE, position = "right")%>%
  	      visIgraphLayout()%>%
  	      visOptions(highlightNearest = TRUE)%>%
  visInteraction(tooltipStyle = 'position: fixed;visibility:hidden;padding: 5px;white-space: nowrap;
   font-family: verdana;font-size:14px;font-color:black;background-color: white;border: 1px solid #808074;')
  	    })       
    }
    return(ntw)
  }
})
visNetworkOutput(outputId="local_network_monitor")   

```

### Heatmap

```{r, echo = FALSE}

output$local_heatmap = renderPlotly({
      values = values()
      heatmaply(percentize(values), dendrogram = 'none', colors = viridis(n = 50, begin = 0, end = 1, direction = 1, option = "plasma"))
      })

plotlyOutput(outputId="local_heatmap")

```

Column {data-width=400}
-------------------------------------

### Metrics 

```{r}
  fillCol(h5("Centralization Scores"),
          tableOutput(outputId = 'table_centr'),
          h5("Centrality Scores"),
          DTOutput(outputId = 'table_values'), flex = c(0.5,1,0.5,5))
```

Communities 
===================================== 

Inputs {.sidebar}
-------------------------------------

```{r}

br()
h4("Network Ties")
# Selection of the edges that will appear in the relation network
checkboxGroupInput("edges_select_comm",
                   label = "Tie Type",
                   choices = list("Is teacher of" = 1,
                                  "Is friend of" = 2,
                                  "Is family of" = 3,
                                  "Studied the work of" = 4,
                                  "Sent letters to" = 5,
                                  #"Is associated with" = 6,
                                  "Is benefactor of" = 7),
                   selected = 1,
                   inline = FALSE)
br()
# Plot Height
h4("Community detection")
# Algorithm for community detection
selectInput("cmnt_dtc_alg", "Algorithm:", choices=c(
                                                    "Cluster Edge Betweenness",
                                                    "Cluster Fast Greedy",
                                                    "Cluster Infomap",
                                                    "Cluster Label Prop",
                                                    "Cluster Leading Eigen",
                                                    "Cluster Louvain",
                                                    #"Cluster Optimal", # Crashes the system! #
                                                    #"Cluster Spinglass",
                                                    "Cluster Walktrap"))

br()
h4("Visualization package")
# Library for community visualization
selectInput("cmnt_vsl_pck", "Library:", choices=c("visNetwork", "igraph"))
#br()
checkboxInput("edges_format", label = "Highlight crossing ties", value = FALSE)
#radioButtons("edges_format", label = h4("Ties format"),
#    choices = list("Communities links highlight" = 1, "Colour by tie type" = 2),
#    selected = 2)
br()
# Plot Height
h4("Appearance")
# Nodes/Label sizes
uiOutput(outputId="labelUI_vnw")
uiOutput(outputId="labelUI_igp")
uiOutput(outputId="nodeUI_vnw")
uiOutput(outputId="nodeUI_igp")
#hr()
#helpText("Set size range of nodes and labels to scale according to the degree of the node, max values for higher degrees and min values for lower degrees")

div(message, style = "color:red")

```

Row
-------------------------------------

### Communities

```{r}

# Community detection

clustering = function(alg, graph){
  if (alg == "Cluster Edge Betweenness") cluster <- cluster_edge_betweenness(graph, bridges = TRUE)
  if (alg == "Cluster Fast Greedy") cluster <- cluster_fast_greedy(graph)
  if (alg == "Cluster Infomap") cluster <- cluster_infomap(graph)
  if (alg == "Cluster Label Prop") cluster <- cluster_label_prop(graph)
  if (alg == "Cluster Leading Eigen") cluster <- cluster_leading_eigen(graph)
  if (alg == "Cluster Louvain") cluster <- cluster_louvain(graph)
  #if (alg == "Cluster Optimal") cluster <- cluster_optimal(graph) # Crashes the system #
  #if (alg == "Cluster Spinglass") cluster <- cluster_spinglass(graph)
  if (alg == "Cluster Walktrap") cluster <- cluster_walktrap(graph)
  return(cluster)
} 

handledClustering = function(alg, graph){
  tryCatch(clustering(alg,graph), 
           #warning = function(w){;},
           error = function(e){message = e;NULL})
}

network_cmnt =  reactive({
  
  # First validate if there are edges (Ties) selected
  validate(
    need(try(!is.null(input$edges_select_comm)), "Please select at least one Tie Type")
  )

  # Use function is_directed
  #directed = is_directed(input$edges_select_comm)
  directed = FALSE
  
  try(g <- graph_from_data_frame(d = edges, directed=directed, vertices = nodes), silent = TRUE)
  
  # ids in nodes are es required to export to Pajek format. Just in case!
  V(g)$id = V(g)$name
  
  # ids in edges are requiered for visUpdateNodes / visRemoveNodes / visUpdateEdges / visRemoveEdges 
  E(g)$id = seq(1:length(E(g)))
  
  # Subsetting according to edges selected
  g_ = subset_graph(input$edges_select_comm, g)
  
  cluster = handledClustering(input$cmnt_dtc_alg, g_)
  
  # Controling the colours of each group
  node_colours = rainbow(summary(cluster$membership)[6])
  setColour = function(x) {substr(node_colours[x],1,nchar(node_colours[x])-2)}

  validate(
    need(try(!is.null(cluster)), 
         paste("The algorithm ",
               input$cmnt_dtc_alg,
               " could not identify communities given the current Phylosophers and Relations"," . ",  message)
         )
  )
  
  # This code is on hold until the requirement for bridges detection is 
  # addressed
  #if (input$cmnt_dtc_alg == "Cluster Edge Betweenness") {
    #Print in console the id's of the edges identified as bridges 
    #print(cluster$bridges)
    #e = length(E(g_)$id)
    #e_bool = sapply(seq(1:e), function(x) x %in% cluster$bridges) + 1
    #print(e_bool)
    #bridges_edge_col = c("#b8f3ff","#ff00fb")[e_bool]  
  #} else 
  
  # In the meanwhile overwriting the default behaviour
  bridges_edge_col  = c("#030000","#ff0400")[igraph::crossing(cluster, g_) + 1]
    
  if (input$cmnt_vsl_pck == "visNetwork") {
    
    output$cmnt_vnw = renderVisNetwork({
  
      #Set label size
      if (is.null(input$labelUI_vnw[1])) min_label = rescaled_value(1.0,2.0,4)
      else min_label = rescaled_value(1.0,2.0,input$labelUI_vnw[1])
      
      if (is.null(input$labelUI_vnw[2])) max_label = rescaled_value(1.0,2.0,6)
      else max_label = rescaled_value(1.0,2.0,input$labelUI_vnw[2])
      
      # Scaling labels
      labsize <- rescale(degree(g_), min(degree(g_)), max(degree(g_)), min_label, max_label)
      V(g_)$label.cex <- labsize
      
      # Assign membership ids to vertex
      V(g_)$community  <- cluster$membership
      
      data <- toVisNetworkData(g_)
      
      # Set node size
      if (is.null(input$nodeUI_vnw[1])) min_node = rescaled_value(20.0,30.0,4)
      else min_node = rescaled_value(20.0,30.0,input$nodeUI_vnw[1])
      
      if (is.null(input$nodeUI_vnw[2])) max_node = rescaled_value(20.0,30.0,6)
      else max_node = rescaled_value(20.0,30.0,input$nodeUI_vnw[2])
      
      # Scaling nodes
      nodesize <- rescale(degree(g_), min(degree(g_)), max(degree(g_)), min_node, max_node)
      data$nodes$size = nodesize
      
      # Setting parameters straight in the data frame for visNetwork
      data$nodes$color.background = sapply(data$nodes$community, FUN = setColour)
        
      # Setting group in visnetwork format
      # data$nodes$group = data$nodes$community
      
      data$nodes$color.border = rep("#000000",length(data$nodes$community))
      
      if (input$edges_format == TRUE) {
        data$edges$color.color = bridges_edge_col
        data$edges$color.highlight = bridges_edge_col
      } else {
        # Setting parameters straight in the data frame for visNetwork
        data$edges$color.color = case_when(
          data$edges$Relation == "is teacher of" ~ '#0000FF',
          data$edges$Relation == "is friend of" ~ '#228B22',
          data$edges$Relation == "is family of" ~ '#FF0000', 
          data$edges$Relation == "studied the work of" ~ '#ff01d9',
          data$edges$Relation == "sent letters to" ~ '#ffbf00',
          #data$edges$Relation == "is associated with" ~ '#14ff03',
          data$edges$Relation == "is benefactor of" ~ '#fff23c'
        )
        
        data$edges$color.highlight = case_when(
          data$edges$Relation == "is teacher of" ~ '#00ffff',
          data$edges$Relation == "is friend of" ~ '#568b22',
          data$edges$Relation == "is family of" ~ '#ff4000',
          data$edges$Relation == "studied the work of" ~ '#d9ff01',
          data$edges$Relation == "sent letters to" ~ '#8400ff',
          #data$edges$Relation == "is associated with" ~ '#ff0314',
          data$edges$Relation == "is benefactor of" ~ '#e53cff'
        )
      }
      

    
      # nodes data.frame for legend
      lnodes <- data.frame(label = c("Male", "Female"),
                           shape = c( "dot"),
                           color = c("#FF6347", "#ffa500"),
                           id = 1:2)
      
      if (directed) arrow = c("to", FALSE, FALSE, "to", "to") else  arrow = rep(as.character(FALSE),5) 
      
      # edges data.frame for legend
      ledges <- data.frame(color = c("#0000FF", "#228B22", "#FF0000", '#ff01d9','#ffbf00'),
                           label = c("is teacher of", "is friend of", "is family of", "studied the work of", "sent letters to"), 
                           arrows =arrow, 
                           font.align = "bottom")
      
      # Shows the name when hovering over the node
      data$nodes$title = paste0('<center><p style = "font-size:14px;font-weight:bold;font-family: verdana;color:',
                                data$nodes$color.background, 
                                ';">',
                                data$nodes$id,
                                '</p></center>', 
                                '<center>Community N: ', '<b>',data$nodes$community,'</b></center>'
                                )
      
      if (directed) {
        
        # Shows the relation when hovering over the edge
        data$edges$title =  paste0('<center><p style = "font-size:14px;font-family:verdana;">',
                                  data$edges$from,
                                  '</p></center>', 
                                  '<center><p style = "font-size:18px;font-weight:bold;font-family: verdana;color:',
                                  data$edges$color.color, 
                                  ';">',
                                  data$edges$Relation,
                                  '</p></center>', 
                                  '<center><p style = "font-size:14px;font-family:verdana;">',
                                  data$edges$to, 
                                  '</p></center>'
                                  )  
        
      } else {
        
        # Shows the relation when hovering over the edge
        data$edges$title =  paste0('<center><p style = "font-size:14px;font-family:verdana;">',
                                  data$edges$to,
                                  '</p></center>', 
                                  '<center><p style = "font-size:18px;font-weight:bold;font-family: verdana;color:',
                                  data$edges$color.color, 
                                  ';">',
                                  data$edges$Relation,
                                  '</p></center>', 
                                  '<center><p style = "font-size:14px;font-family:verdana;">',
                                  data$edges$from, 
                                  '</p></center>'
                                  )
        
      }
    
      withProgress(message = 'Creating graph', style = 'notification', value = 0.1, {
        Sys.sleep(0.25)
        incProgress(0.6, detail = paste("Running VisNetwork"))
    		mod <- round(modularity(cluster),3)
    		subTitle = paste0("MODULARITY: ", mod)
    		
    		# Setting seed is important so the graph is always with the same configuration when starts
        set.seed(123)
        
    		# Visnetwork graph creation
    		visNetwork(nodes = data$nodes, edges = data$edges, main=subTitle)%>%
    		  visNodes(shape = "dot") %>%
    		  visEdges(arrows =list(to = list(enabled = directed))) %>%
          #visLegend(addEdges = ledges, addNodes = lnodes, useGroups = FALSE, width = 0.1, zoom = FALSE, position = "right")%>%
    		  visIgraphLayout()%>%
    		  visOptions(highlightNearest = TRUE)%>%
visInteraction(tooltipStyle = 'position: fixed;visibility:hidden;padding: 5px;white-space: nowrap;
 font-family: verdana;font-size:14px;font-color:black;background-color: white;border: 1px solid #808074;')
      })
    })
    return(visNetworkOutput(outputId="cmnt_vnw"))
  } 

  if (input$cmnt_vsl_pck == "igraph") {
    
    output$cmnt_igp = renderPlot({
    
      #Set label size
      if (is.null(input$labelUI_igp[1])) min_label = rescaled_value(0.7,1.2,4)
      else min_label = rescaled_value(0.7,1.2,input$labelUI_igp[1])
      
      if (is.null(input$labelUI_igp[2])) max_label = rescaled_value(0.7,1.2,6)
      else max_label = rescaled_value(0.7,1.2,input$labelUI_igp[2])
      
      # Scaling labels
      labsize <- rescale(degree(g_), min(degree(g_)), max(degree(g_)), min_label, max_label)
      V(g_)$label.cex <- labsize
      
      # Assign membership ids to vertex
      V(g_)$community  <- cluster$membership
      
      data <- toVisNetworkData(g_)
      
      if (input$edges_format == FALSE) {
        # Setting parameters straight in the data frame for visNetwork
        bridges_edge_col = case_when(
          data$edges$Relation == "is teacher of" ~ '#0000FF',
          data$edges$Relation == "is friend of" ~ '#228B22',
          data$edges$Relation == "is family of" ~ '#FF0000', 
          data$edges$Relation == "studied the work of" ~ '#ff01d9',
          data$edges$Relation == "sent letters to" ~ '#ffbf00',
          #data$edges$Relation == "is associated with" ~ '#14ff03',
          data$edges$Relation == "is benefactor of" ~ '#fff23c'
        )
      }
      
      # Set node size
      if (is.null(input$nodeUI_igp[1])) min_node = rescaled_value(4.0,9.0,4)
      else min_node = rescaled_value(4.0,9.0,input$nodeUI_igp[1])
      
      if (is.null(input$nodeUI_igp[2])) max_node = rescaled_value(4.0,9.0,6)
      else max_node = rescaled_value(4.0,9.0,input$nodeUI_igp[2])
      
      # Scaling nodes
      nodesize <- rescale(degree(g_), min(degree(g_)), max(degree(g_)), min_node, max_node)
      V(g_)$size <- nodesize
    
      
      withProgress(message = 'Creating graph', style = 'notification', value = 0.1, {
        Sys.sleep(0.25)
        incProgress(0.6, detail = paste("Running igraph"))
        mod <- round(modularity(cluster),3)
        subTitle = paste0("MODULARITY: ", mod)
        # Setting seed is important so the graph is always with the same configuration when starts
        set.seed(123)
        coords <- layout_(g_, nicely())
        new_cols <- node_colours[membership(cluster)]
        plot(x=cluster,
             y=g_,
             col = new_cols, 
             main = subTitle, 
             layout = matrix(c(coords[,1], -coords[,2]), 
                             nrow = length(coords[,1]), 
                             ncol = 2, 
                             byrow = FALSE, 
                             dimnames = list()), 
             edge.color = bridges_edge_col)
        })
    })
    return(plotOutput(outputId="cmnt_igp"))
  }
})    

output$graph_cmnt <- renderUI({
  network_cmnt()
})

output$labelUI_vnw <- renderUI({
  if (input$cmnt_vsl_pck == "visNetwork") {
    if (!is.null(input$labelUI_vnw)) sliderInput(inputId = "labelUI_vnw", label = "Label Size", min = 0.0, max = 10.0, value = c(4, 6),ticks = TRUE, step = 1)
    else sliderInput(inputId = "labelUI_vnw", label = "Label Size", min = 0.0, max = 10.0, value = c(4, 6),ticks = TRUE, step = 1)
  } 
})

output$nodeUI_vnw <- renderUI({
  if (input$cmnt_vsl_pck == "visNetwork") {
    if (!is.null(input$nodeUI_vnw)) sliderInput(inputId = "nodeUI_vnw", label = "Node Size", min = 0.0, max = 10.0, value = c(4, 6),ticks = TRUE, step = 1)
    else sliderInput(inputId = "nodeUI_vnw", label = "Node Size", min = 0.0, max = 10.0, value = c(4, 6),ticks = TRUE, step = 1)
  }
})

output$labelUI_igp <- renderUI({
  if (input$cmnt_vsl_pck == "igraph") {
    if (!is.null(input$labelUI_igp)) sliderInput(inputId = "labelUI_igp", label = "Label Size", min = 0.0, max = 10.0, value = c(4, 6),ticks = TRUE, step = 1)
    else sliderInput(inputId = "labelUI_igp", label = "Label Size",min = 0.0, max = 10.0, value = c(4, 6),ticks = TRUE, step = 1)
  } 
})

output$nodeUI_igp <- renderUI({
  if (input$cmnt_vsl_pck == "igraph") {
    if (!is.null(input$nodeUI_igp)) sliderInput(inputId = "nodeUI_igp", label = "Node Size", min = 0.0, max = 10.0, value = c(4, 6),ticks = TRUE, step = 1)
    else sliderInput(inputId = "nodeUI_igp", label = "Node Size", min = 0.0, max = 10.0, value = c(4, 6),ticks = TRUE, step = 1)
  }
})
  
uiOutput(outputId="graph_cmnt")

```